#!/usr/bin/perl
## Copyright (C) 2013 Carnë Draug <carandraug+dev@gmail.com>
##
## This program is free software; you can redistribute it and/or modify
## it under the terms of the GNU General Public License as published by
## the Free Software Foundation; either version 3 of the License, or
## (at your option) any later version.
##
## This program is distributed in the hope that it will be useful,
## but WITHOUT ANY WARRANTY; without even the implied warranty of
## MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
## GNU General Public License for more details.
##
## You should have received a copy of the GNU General Public License
## along with this program; if not, see <http://www.gnu.org/licenses/>.

use 5.010;                      # Use Perl 5.10
use strict;                     # Enforce some good programming rules
use warnings;                   # Replacement for the -w flag, but lexically scoped
use File::Spec;                 # Perform operation on file names
use Getopt::Long;               # Parse program arguments
use Bio::SeqIO;                 # Handler for SeqIO formats

## This script compares the new data against some reference. In our case, the reference
## is Marzluff, W.F., Gongidi, P., Woods, K.R., Jin, J., Maltais, l.J. (2002) The human
## and mouse replication-dependent histone genes. Genomics (80) 5:487--498
## doi:10.1006/geno.2002.6850

## Check input options
my %path = ("sequences" => "",
            "results"   => "");
my $email;
GetOptions(
            "sequences=s" => \$path{sequences},
            "results=s"   => \$path{results},
            'email=s'     => \$email,
          ) or die "Error processing options.";
for (keys %path) {
  die "No path for $_ specified. Use the --$_ option." unless $path{$_};
}
## we don't check the email, that's optional later on

my %reference = (
  ## all H2A sequences from Table 2: Histone H2A protein variants (page 494)
  H2Aconsensus => "SGRGKQGGKARAKAKTRSSRAGLQFPVGRVHRLLRKGNYAERVGAGAPVYLAAVLEYLTAEILELAGNAARDNKKTRIIPRHLQLAIRNDEELNKLLGKVTIAQGGVLPNIQAVLLPKKTESHHKAKGK",
  HIST1H2AA => "SGRGKQGGKARAKSKSRSSRAGLQFPVGRIHRLLRKGNYAERIGAGAPVYLAAVLEYLTAEILELAGNASRDNKKTRIIPRHLQLAIRNDEELNKLLGGVTIAQGGVLPNIQAVLLPKKTESHHHKAQSK",
  HIST1H2AB => "SGRGKQGGKARAKAKTRSSRAGLQFPVGRVHRLLRKGNYAERVGAGAPVYLAAVLEYLTAEILELAGNAARDNKKTRIIPRHLQLAIRNDEELNKLLGRVTIAQGGVLPNIQAVLLPKKTESHHKAKGK",
  HIST1H2AC => "SGRGKQGGKARAKAKSRSSRAGLQFPVGRVHRLLRKGNYAERVGAGAPVYLAAVLEYLTAEILELAGNAARDNKKTRIIPRHLQLAIRNDEELNKLLGRVTIAQGGVLPNIQAVLLPKKTESHHKAKGK",
  HIST1H2AD => "SGRGKQGGKARAKAKTRSSRAGLQFPVGRVHRLLRKGNYAERVGAGAPVYLAAVLEYLTAEILELAGNAARDNKKTRIIPRHLQLAIRNDEELNKLLGKVTIAQGGVLPNIQAVLLPKKTESHHKAKGK",
  HIST1H2AE => "SGRGKQGGKARAKAKTRSSRAGLQFPVGRVHRLLRKGNYAERVGAGAPVYLAAVLEYLTAEILELAGNAARDNKKTRIIPRHLQLAIRNDEELNKLLGRVTIAQGGVLPNIQAVLLPKKTESHHKAKGK",
  ## a mistake on the paper. Table 2 says HIST1H2AF but table 1 says HIST1H2AG (table 1 is right)
  HIST1H2AG => "SGRGKQGGKARAKAKTRSSRAGLQFPVGRVHRLLRKGNYAERVGAGAPVYLAAVLEYLTAEILELAGNAARDNKKTRIIPRHLQLAIRNDEELNKLLGKVTIAQGGVLPNIQAVLLPKKTESHHKAKGK",
  HIST1H2AH => "SGRGKQGGKARAKAKTRSSRAGLQFPVGRVHRLLRKGNYAERVGAGAPVYLAAVLEYLTAEILELAGNAARDNKKTRIIPRHLQLAIRNDEELNKLLGKVTIAQGGVLPNIQAVLLPKKTESHHKAKG",
  HIST1H2AI => "SGRGKQGGKARAKAKTRSSRAGLQFPVGRVHRLLRKGNYAERVGAGAPVYLAAVLEYLTAEILELAGNAARDNKKTRIIPRHLQLAIRNDEELNKLLGKVTIAQGGVLPNIQAVLLPKKTESHHKAKGK",
  HIST1H2AJ => "SGRGKQGGKARAKAKTRSSRAGLQFPVGRVHRLLRKGNYAERVGAGAPVYLAAVLEYLTAEILELAGNAARDNKKTRIIPRHLQLAIRNDEELNKLLGKVTIAQGGVLPNIQAVLLPKKTESHHKTKG",
  HIST1H2AK => "SGRGKQGGKARAKAKTRSSRAGLQFPVGRVHRLLRKGNYAERVGAGAPVYLAAVLEYLTAEILELAGNAARDNKKTRIIPRHLQLAIRNDEELNKLLGKVTIAQGGVLPNIQAVLLPKKTESHHKAKGK",
  HIST1H2AL => "SGRGKQGGKARAKAKTRSSRAGLQFPVGRVHRLLRKGNYAERVGAGAPVYLAAVLEYLTAEILELAGNAARDNKKTRIIPRHLQLAIRNDEELNKLLGKVTIAQGGVLPNIQAVLLPKKTESHHKAKGK",
  HIST1H2AM => "SGRGKQGGKARAKAKTRSSRAGLQFPVGRVHRLLRKGNYAERVGAGAPVYLAAVLEYLTAEILELAGNAARDNKKTRIIPRHLQLAIRNDEELNKLLGKVTIAQGGVLPNIQAVLLPKKTESHHKAKGK",
  HIST2H2AA => "SGRGKQGGKARAKAKSRSSRAGLQFPVGRVHRLLRKGNYAERVGAGAPVYMAAVLEYLTAEILELAGNAARDNKKTRIIPRHLQLAIRNDEELNKLLGKVTIAQGGVLPNIQAVLLPKKTESHHKAKGK",
  HIST2H2AB => "SGRGKQGGKARAKAKSRSSRAGLQFPVGRVHRLLRKGNYAERVGAGAPVYMAAVLEYLTAEILELAGNAARDNKKTRIIPRHLQLAVRNDEELNKLLGGVTIAQGGVLPNIQAVLLPKKTESHKPGPNK",
  HIST2H2AC => "SGRGKQGGKARAKAKSRSSRAGLQFPVGRVHRLLRKGNYAERVGAGAPVYMAAVLEYLTAEILELAGNAARDNKKTRIIPRHLQLAIRNDEELNKLLGKVTIAQGGVLPNIQAVLLPKKTESHHKAKSK",
  HIST3H2A  => "SGRGKQGGKARAKAKSRSSRAGLQFPVGRVHRLLRKGNYAERVGAGAPVYMAAVLEYLTAEILELAGNAARDNKKTRIIPRHLQLAIRNDEELNKLLGRVTIAQGGVLPNIQAVLLPKKTESHHKAKGK",

  ## all H2B sequences from Table 3: Histone H2B protein variants (page 495)
  H2Bconsensus => "PEPAKSAPAPKKGSKKAVTKAQKKDGKKRKRSRKESYSVYVYKVLKQVHPDTGISSKAMGIMNSFVNDIFERIAGEASRLAHYNKRSTITSREIQTAVRLLLPGELAKHAVSEGTKAVTKYTSSK",
  HIST1H2BA => "PEVSSKGATISKKGFKKAVVKTQKKEGKKRKRTRKESYSIYIYKVLKQVHPDTGISSKAMSIMNSFVTDIFERIASEASRLAHYSKRSTISSREIQTAVRLLLPGELAKHAVSEGTKAVTKYTSSN",
  HIST1H2BB => "PEPAKSAPAPKKGSKKAITKAQKKDGKKRKRSRKESYSIYVYKVLKQVHPDTGISSKAMGIMNSFVNDIFERIAGEASRLAHYNKRSTITSREIQTAVRLLLPGELAKHAVSEGTKAVTKYTSSK",
  HIST1H2BC => "PEPAKSAPAPKKGSKKAVTKAQKKDGKKRKRSRKESYSVYVYKVLKQVHPDTGISSKAMGIMNSFVNDIFERIAGEASRLAHYNKRSTITSREIQTAVRLLLPGELAKHAVSEGTKAVTKYTSSK",
  HIST1H2BD => "PEPTKSAPAPKKGSKKAVTKAQKKDGKKRKRSRKESYSVYVYKVLKQVHPDTGISSKAMGIMNSFVNDIFERIAGEASRLAHYNKRSTITSREIQTAVRLLLPGELAKHAVSEGTKAVTKYTSSK",
  HIST1H2BE => "PEPAKSAPAPKKGSKKAVTKAQKKDGKKRKRSRKESYSVYVYKVLKQVHPDTGISSKAMGIMNSFVNDIFERIAGEASRLAHYNKRSTITSREIQTAVRLLLPGELAKHAVSEGTKAVTKYTSSK",
  HIST1H2BF => "PEPAKSAPAPKKGSKKAVTKAQKKDGKKRKRSRKESYSVYVYKVLKQVHPDTGISSKAMGIMNSFVNDIFERIAGEASRLAHYNKRSTITSREIQTAVRLLLPGELAKHAVSEGTKAVTKYTSSK",
  HIST1H2BG => "PEPAKSAPAPKKGSKKAVTKAQKKDGKKRKRSRKESYSVYVYKVLKQVHPDTGISSKAMGIMNSFVNDIFERIAGEASRLAHYNKRSTITSREIQTAVRLLLPGELAKHAVSEGTKAVTKYTSSK",
  HIST1H2BH => "PDPAKSAPAPKKGSKKAVTKAQKKDGKKRKRSRKESYSVYVYKVLKQVHPDTGISSKAMGIMNSFVNDIFERIAGEASRLAHYNKRSTITSREIQTAVRLLLPGELAKHAVSEGTKAVTKYTSSK",
  HIST1H2BI => "PEPAKSAPAPKKGSKKAVTKAQKKDGKKRKRSRKESYSVYVYKVLKQVHPDTGISSKAMGIMNSFVNDIFERIAGEASRLAHYNKRSTITSREIQTAVRLLLPGELAKHAVSEGTKAVTKYTSSK",
  HIST1H2BJ => "PEPAKSAPAPKKGSKKAVTKAQKKDGKKRKRSRKESYSVYVYKVLKQVHPDTGISSKAMGIMNSFVNDIFERIAGEASRLAHYNKRSTITSREIQTAVRLLLPGELAKHAVSEGTKAVTKYTSAK",
  HIST1H2BK => "PEPAKSAPAPKKGSKKAVTKAQKKDGKKRKRSRKESYSVYVYKVLKQVHPDTGISSKAMGIMNSFVNDIFERIAGEASRLAHYNKRSTITSREIQTAVRLLLPGELAKHAVSEGTKAVTKYTSAK",
  HIST1H2BL => "PELAKSAPAPKKGSKKAVTKAQKKDGKKRKRSRKESYSVYVYKVLKQVHPDTGISSKAMGIMNSFVNDIFERIASEASRLAHYNKRSTITSREIQTAVRLLLPGELAKHAVSEGTKAVTKYTSSK",
  HIST1H2BM => "PEPVKSAPVPKKGSKKAINKAQKKDGKKRKRSRKESYSVYVYKVLKQVHPDTGISSKAMGIMNSFVNDIFERIAGEASRLAHYNKRSTITSREIQTAVRLLLPGELAKHAVSEGTKAVTKYTSSK",
  HIST1H2BN => "PEPSKSAPAPKKGSKKAVTKAQKKDGKKRKRSRKESYSVYVYKVLKQVHPDTGISSKAMGIMNSFVNDIFERIAGEASRLAHYNKRSTITSREIQTAVRLLLPGELAKHAVSEGTKAVTKYTSSK",
  HIST1H2BO => "PDPAKSAPAPKKGSKKAVTKAQKKDGKKRKRSRKESYSIYVYKVLKQVHPDTGISSKAMGIMNSFVNDIFERIAGEASRLAHYNKRSTITSREIQTAVRLLLPGELAKHAVSEGTKAVTKYTSSK",
  HIST2H2BE => "PEPAKSAPAPKKGSKKAVTKAQKKDGKKRKRSRKESYSIYVYKVLKQVHPDTGISSKAMGIMNSFVNDIFERIAGEASRLAHYNKRSTITSREIQTAVRLLLPGELAKHAVSEGTKAVTKYTSSK",
  HIST3H2BB => "PDPSKSAPAPKKGSKKAVTKAQKKDGKKRKRGRKESYSIYVYKVLKQVHPDTGISSKAMGIMNSFVNDIFERIASEASRLAHYNKRSTITSREVQTAVRLLLPGELAKHAVSEGTKAVTKYTSSK",

  ## There was no H3 protein sequence on the paper. Instead, it's written on page 489:
  ##
  ##    ... the histone H3 genes encode the two variants previously described [15] ...
  ##
  ## The reference target is "Zweidler, A. (1984). Core histone variants of the mouse: primary
  ## structure and expression. In Histone Genes: Structure, Organization and Regulation (G. Stein,
  ## W.Stein W. F. Marzluff, Eds), pp.373-395. John Wiley and Sons, New York". The correct page
  ## numbers are actually 339-371. And on page 494:
  ##
  ##    There are two variants encoded by the histone H3 genes, H3.1 and H3.2. These
  ##    differ in a single amino acid change at position 96, a cysteine in H3.1 genes
  ##    and a serine in H3.2 genes. The functional histone H3 gene (HIST2H3C) in the
  ##    HIST2 cluster on chromosome 1 encodes the H3.2 protein and all 11 histone H3
  ##    genes in the HIST1 cluster encode the H3.1 protein.
  ##
  ## However, on Table 1, there's only mention of 10 histone H3 genes for the HIST1 cluster. There
  ## is also mention of a third H3. Previously on page 492:
  ##
  ##    HIST3H3, described previously as a solitary gene [19], encodes a novel histone
  ##    H3 protein, with the serine at position 96 and four additional changes (A24V,
  ##    V71M, A98S, A111V)
  ##
  ## This leads to a total of 3 unique H3 protein sequences
  HIST1H3A => "ARTKQTARKSTGGKAPRKQLATKAARKSAPATGGVKKPHRYRPGTVALREIRRYQKSTELLIRKLPFQRLVREIAQDFKTDLRFQSSAVMALQEACEAYLVGLFEDTNLCAIHAKRVTIMPKDIQLARRIRGERA",
  HIST1H3B => "ARTKQTARKSTGGKAPRKQLATKAARKSAPATGGVKKPHRYRPGTVALREIRRYQKSTELLIRKLPFQRLVREIAQDFKTDLRFQSSAVMALQEACEAYLVGLFEDTNLCAIHAKRVTIMPKDIQLARRIRGERA",
  HIST1H3C => "ARTKQTARKSTGGKAPRKQLATKAARKSAPATGGVKKPHRYRPGTVALREIRRYQKSTELLIRKLPFQRLVREIAQDFKTDLRFQSSAVMALQEACEAYLVGLFEDTNLCAIHAKRVTIMPKDIQLARRIRGERA",
  HIST1H3D => "ARTKQTARKSTGGKAPRKQLATKAARKSAPATGGVKKPHRYRPGTVALREIRRYQKSTELLIRKLPFQRLVREIAQDFKTDLRFQSSAVMALQEACEAYLVGLFEDTNLCAIHAKRVTIMPKDIQLARRIRGERA",
  HIST1H3E => "ARTKQTARKSTGGKAPRKQLATKAARKSAPATGGVKKPHRYRPGTVALREIRRYQKSTELLIRKLPFQRLVREIAQDFKTDLRFQSSAVMALQEACEAYLVGLFEDTNLCAIHAKRVTIMPKDIQLARRIRGERA",
  HIST1H3F => "ARTKQTARKSTGGKAPRKQLATKAARKSAPATGGVKKPHRYRPGTVALREIRRYQKSTELLIRKLPFQRLVREIAQDFKTDLRFQSSAVMALQEACEAYLVGLFEDTNLCAIHAKRVTIMPKDIQLARRIRGERA",
  HIST1H3G => "ARTKQTARKSTGGKAPRKQLATKAARKSAPATGGVKKPHRYRPGTVALREIRRYQKSTELLIRKLPFQRLVREIAQDFKTDLRFQSSAVMALQEACEAYLVGLFEDTNLCAIHAKRVTIMPKDIQLARRIRGERA",
  HIST1H3H => "ARTKQTARKSTGGKAPRKQLATKAARKSAPATGGVKKPHRYRPGTVALREIRRYQKSTELLIRKLPFQRLVREIAQDFKTDLRFQSSAVMALQEACEAYLVGLFEDTNLCAIHAKRVTIMPKDIQLARRIRGERA",
  HIST1H3I => "ARTKQTARKSTGGKAPRKQLATKAARKSAPATGGVKKPHRYRPGTVALREIRRYQKSTELLIRKLPFQRLVREIAQDFKTDLRFQSSAVMALQEACEAYLVGLFEDTNLCAIHAKRVTIMPKDIQLARRIRGERA",
  HIST1H3J => "ARTKQTARKSTGGKAPRKQLATKAARKSAPATGGVKKPHRYRPGTVALREIRRYQKSTELLIRKLPFQRLVREIAQDFKTDLRFQSSAVMALQEACEAYLVGLFEDTNLCAIHAKRVTIMPKDIQLARRIRGERA",
  HIST2H3C => "ARTKQTARKSTGGKAPRKQLATKAARKSAPATGGVKKPHRYRPGTVALREIRRYQKSTELLIRKLPFQRLVREIAQDFKTDLRFQSSAVMALQEASEAYLVGLFEDTNLCAIHAKRVTIMPKDIQLARRIRGERA",
  HIST3H3  => "ARTKQTARKSTGGKAPRKQLATKVARKSAPATGGVKKPHRYRPGTVALREIRRYQKSTELLIRKLPFQRLMREIAQDFKTDLRFQSSAVMALQEASESYLVGLFEDTNLCVIHAKRVTIMPKDIQLARRIRGERA",

  ## There was also no H4 protein sequence on the paper. Instead, on the caption of Table 1 it is said
  ##
  ##    The human H4 gene described by Akasaka and coworkers [56] is HISTH4I[sic]
  ##
  ## Then, on page 489, it is written
  ##
  ##    all the histone H4 genes encode the same protein
  ##
  ## thus logically stating that all have the same sequence from reference 56 which targets "Akasaka, T.,
  ## et al. (1997). A recurring translocation, t(3;6)(q27;p21), in non-Hodgkin's lymphoma results in
  ## replacement of the 5' regulatory region of BCL6 with a novel H4 histone gene. Cancer Res. 57: 7--12."
  HIST1H4A => "SGRGKGGKGLGKGGAKRHRKVLRDNIQGITKPAIRRLARRGGVKRISGLIYEETRGVLKVFLENVIRDAVTYTEHAKRKTVTAMDVVYALKRQGRTLYGFGG",
  HIST1H4B => "SGRGKGGKGLGKGGAKRHRKVLRDNIQGITKPAIRRLARRGGVKRISGLIYEETRGVLKVFLENVIRDAVTYTEHAKRKTVTAMDVVYALKRQGRTLYGFGG",
  HIST1H4C => "SGRGKGGKGLGKGGAKRHRKVLRDNIQGITKPAIRRLARRGGVKRISGLIYEETRGVLKVFLENVIRDAVTYTEHAKRKTVTAMDVVYALKRQGRTLYGFGG",
  HIST1H4D => "SGRGKGGKGLGKGGAKRHRKVLRDNIQGITKPAIRRLARRGGVKRISGLIYEETRGVLKVFLENVIRDAVTYTEHAKRKTVTAMDVVYALKRQGRTLYGFGG",
  HIST1H4E => "SGRGKGGKGLGKGGAKRHRKVLRDNIQGITKPAIRRLARRGGVKRISGLIYEETRGVLKVFLENVIRDAVTYTEHAKRKTVTAMDVVYALKRQGRTLYGFGG",
  HIST1H4F => "SGRGKGGKGLGKGGAKRHRKVLRDNIQGITKPAIRRLARRGGVKRISGLIYEETRGVLKVFLENVIRDAVTYTEHAKRKTVTAMDVVYALKRQGRTLYGFGG",
  HIST1H4G => "SGRGKGGKGLGKGGAKRHRKVLRDNIQGITKPAIRRLARRGGVKRISGLIYEETRGVLKVFLENVIRDAVTYTEHAKRKTVTAMDVVYALKRQGRTLYGFGG",
  HIST1H4H => "SGRGKGGKGLGKGGAKRHRKVLRDNIQGITKPAIRRLARRGGVKRISGLIYEETRGVLKVFLENVIRDAVTYTEHAKRKTVTAMDVVYALKRQGRTLYGFGG",
  HIST1H4I => "SGRGKGGKGLGKGGAKRHRKVLRDNIQGITKPAIRRLARRGGVKRISGLIYEETRGVLKVFLENVIRDAVTYTEHAKRKTVTAMDVVYALKRQGRTLYGFGG",
  HIST1H4J => "SGRGKGGKGLGKGGAKRHRKVLRDNIQGITKPAIRRLARRGGVKRISGLIYEETRGVLKVFLENVIRDAVTYTEHAKRKTVTAMDVVYALKRQGRTLYGFGG",
  HIST1H4K => "SGRGKGGKGLGKGGAKRHRKVLRDNIQGITKPAIRRLARRGGVKRISGLIYEETRGVLKVFLENVIRDAVTYTEHAKRKTVTAMDVVYALKRQGRTLYGFGG",
  HIST1H4L => "SGRGKGGKGLGKGGAKRHRKVLRDNIQGITKPAIRRLARRGGVKRISGLIYEETRGVLKVFLENVIRDAVTYTEHAKRKTVTAMDVVYALKRQGRTLYGFGG",
  HIST2H4  => "SGRGKGGKGLGKGGAKRHRKVLRDNIQGITKPAIRRLARRGGVKRISGLIYEETRGVLKVFLENVIRDAVTYTEHAKRKTVTAMDVVYALKRQGRTLYGFGG",
  HIST4H4  => "SGRGKGGKGLGKGGAKRHRKVLRDNIQGITKPAIRRLARRGGVKRISGLIYEETRGVLKVFLENVIRDAVTYTEHAKRKTVTAMDVVYALKRQGRTLYGFGG",

  "coding genes" => [qw(HIST1H2AA HIST1H2AB HIST1H2AC HIST1H2AD HIST1H2AE HIST1H2AG HIST1H2AH
                        HIST1H2AI HIST1H2AJ HIST1H2AK HIST1H2AL HIST1H2AM HIST2H2AA HIST2H2AB
                        HIST2H2AC HIST2H2A
                        
                        HIST1H2BA HIST1H2BB HIST1H2BC HIST1H2BD HIST1H2BE HIST1H2BF HIST1H2BG
                        HIST1H2BH HIST1H2BI HIST1H2BJ HIST1H2BK HIST1H2BL HIST1H2BM HIST1H2BN
                        HIST1H2BO HIST2H2BE HIST3H2BB
                        
                        HIST1H3A  HIST1H3B  HIST1H3C  HIST1H3D  HIST1H3E  HIST1H3F  HIST1H3G
                        HIST1H3H  HIST1H3I  HIST1H3J  HIST2H3C  HIST3H3
                        
                        HIST1H4A  HIST1H4B  HIST1H4C  HIST1H4D  HIST1H4E  HIST1H4F  HIST1H4G
                        HIST1H4H  HIST1H4I  HIST1H4J  HIST1H4K  HIST1H4L  HIST2H4   HIST4H4)],

  "pseudo genes" => [qw(HIST2H2BA HIST2H2BB HIST2H2BC HIST2H2BD HIST3H2BA HIST2H3A  HIST1H3B)],
);

## Write down results
my $var_path = File::Spec->catdir($path{results}, "variables-cluster_stats.tex");
open (my $var_fh, ">", $var_path) or die "Could not open $var_path for writing: $!";



close ($var_fh) or die "Couldn't close $var_path after writing: $!";


## This check is an interesting check, not part of the publication. It checks for the
## differences between the sequences talked about the paper, and the actual sequences
## from the referenced accession numbers. That's how we found the mistake between
## HIST1H2AF and HIST1H2AG
if ($email) {
  my %ref_acc = (
    ## accession numbers from table 1
    HIST1H2AA => "AY131982",
    HIST1H2AB => "AY131983",
    HIST1H2AC => "AY131984",
    HIST1H2AD => "AY131985",
    HIST1H2AE => "AY131986",
    HIST1H2AG => "AY131987",
    HIST1H2AH => "AY131988",
    HIST1H2AI => "AY131989",
    HIST1H2AJ => "AY131990",
    HIST1H2AK => "AY131991",
    HIST1H2AL => "AY131992",
    HIST1H2AM => "AY131993",
    HIST2H2AA => "AY131971",
    HIST2H2AB => "AY131972",
    HIST2H2AC => "AY131973",
    HIST3H2A  => "AY131974",

    HIST1H2BA => "AF531284",
    HIST1H2BC => "AF531285",
    HIST1H2BD => "AF531286",
    HIST1H2BE => "AF531287",
    HIST1H2BF => "AF531289",
    HIST1H2BG => "AF531290",
    HIST1H2BH => "AF531291",
    HIST1H2BI => "AF531292",
    HIST1H2BJ => "AF531293",
    HIST1H2BK => "AF531294",
    HIST1H2BL => "AF531295",
    HIST1H2BM => "AF531296",
    HIST1H2BN => "AF531297",
    HIST1H2BO => "AF531298",
    HIST2H2BE => "AY131979",
    HIST3H2BB => "AY131981",

    HIST1H3A  => "AF531274",
    HIST1H3B  => "AF531275",
    HIST1H3C  => "AF531276",
    HIST1H3D  => "AF531277",
    HIST1H3E  => "AF531278",
    HIST1H3F  => "AF531279",
    HIST1H3G  => "AF531280",
    HIST1H3H  => "AF531281",
    HIST1H3I  => "AF531282",
    HIST1H3J  => "AF531283",
    HIST2H3C  => "AF531307",
    HIST3H3   => "AF531308",

    HIST1H4A  => "AY128654",
    HIST1H4B  => "AY128655",
    HIST1H4C  => "AY128656",
    HIST1H4D  => "AY128657",
    HIST1H4E  => "AY128658",
    HIST1H4F  => "AY128659",
    HIST1H4G  => "AY128660",
    HIST1H4H  => "AY128661",
    HIST1H4I  => "AY128662",
    HIST1H4J  => "AY128663",
    HIST1H4K  => "AY128664",
    HIST1H4L  => "AY128665",
    HIST2H4   => "AF525682",
    HIST4H4   => "AY128653",
  );
  require Bio::DB::EUtilities;
  my $mistakes = 0;
  foreach my $symbol (keys %ref_acc) {
    my $fetcher = Bio::DB::EUtilities->new(
                                           -eutil   => "efetch",
                                           -db      => "nucleotide",
                                           -id      => [$ref_acc{$symbol}],
                                           -retmode => "text",
                                           -email   => $email,
                                           -rettype => "gb",
                                           );
    my $response = $fetcher->get_Response->content;
    open(my $seq_fh, "<", \$response) or die "Could not open sequences string for reading: $!";
    my $parser = Bio::SeqIO->new(
                                 -fh     => $seq_fh,
                                 -format => "genbank",
                                 );
    my $seq = $parser->next_seq; # we know there's only 1 sequence
    my ($feature) = $seq->get_SeqFeatures("CDS");
    my ($protein) = $feature->get_tag_values("translation");

    ## substr - because when dealing with histones, we never count the first
    ##residue and so we need to "unfix" the annotation
    if (substr ($protein, 1) ne $reference{$symbol}) {
      say "Found different sequences for $symbol";
      $mistakes++;
    }
  }
  say "Total number of mistakes found is: $mistakes";
}

